name: mech
description: mech is a dart library that provides helpers and more features
version: 0.1.0
homepage: https://github.com/gokuzhan/mech.git
maintainer: Gokul Kannan (@gokuzhan)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: